### ISSUE TITLE
Cron Schedule when Flat tables are disabled

### ISSUE THREAD

**Issue by lamasfoker** [koongo-com/magento2-data-feed-manager#11]
In the [docu](https://github.com/koongo-com/magento2-data-feed-manager/blob/main/install.md#if-you-want-to-deactivate-the-flat-catalog-please-add-the-command-below-into-cron) it's written:
>If you want to deactivate the Flat Catalog, please add the command below into CRON

Okay, but with which schedule do I have to put the command in the cron? With * * * * *?

**Comment by lamasfoker** [comment]
@IlyaZha can you take a look a this, please?

**Comment by pecinaon** [comment]
Have a nice day,

it's up to you how often you want to make updates to your product changes.

It depends more on the frequency of changes in your warehouse for example. 

Example for every 5th minute:

`
*/5 * * * *
`


Thanks.
