### ISSUE TITLE
Problem with value evaluation if attribute contains '

### ISSUE THREAD

**Issue by MrTieGuy06** [koongo-com/magento2-data-feed-manager#22]
Hello there!

When adding attribute compositions for a Profile, and an atrribute value contains the `'` character, it throws an exception, as it closes the parameter in eval().

This example value
<img width="1168" alt="Scherm­afbeelding 2024-12-03 om 11 18 28" src="https://github.com/user-attachments/assets/d3c4bdb7-80da-41c0-9eb7-0ed49852a7b2">

Results in this exception:
`[2024-12-03T09:42:32.644093+00:00] main.CRITICAL: ParseError: syntax error, unexpected identifier "Angelo" in /public_html/vendor/koongo-com/magento2-data-feed-manager/src/Nostress/Koongo/Model/Data/Transformation/Xml.php(540) : eval()'d code:1
#0 /public_html/vendor/koongo-com/magento2-data-feed-manager/src/Nostress/Koongo/Model/Data/Transformation/Xml.php(449): Nostress\Koongo\Model\Data\Transformation\Xml->evaluateMathExpressions()
#1 /public_html/vendor/koongo-com/magento2-data-feed-manager/src/Nostress/Koongo/Model/Data/Transformation/Xml.php(348): Nostress\Koongo\Model\Data\Transformation\Xml->getAttributeValue()
#2 /public_html/vendor/koongo-com/magento2-data-feed-manager/src/Nostress/Koongo/Model/Data/Transformation/Xml.php(278): Nostress\Koongo\Model\Data\Transformation\Xml->processCustomAttributes()
#3 /public_html/vendor/koongo-com/magento2-data-feed-manager/src/Nostress/Koongo/Model/Channel/Profile/Processor.php(168): Nostress\Koongo\Model\Data\Transformation\Xml->transform()
#4 /public_html/vendor/koongo-com/magento2-data-feed-manager/src/Nostress/Koongo/Model/Channel/Profile/Processor.php(134): Nostress\Koongo\Model\Channel\Profile\Processor->loadAndPrepareProducts()
#5 /public_html/vendor/koongo-com/magento2-data-feed-manager/src/Nostress/Koongo/Model/Channel/Profile/Manager.php(201): Nostress\Koongo\Model\Channel\Profile\Processor->run()
#6 /public_html/vendor/koongo-com/magento2-data-feed-manager/src/Nostress/Koongo/Model/Channel/Profile/Manager.php(184): Nostress\Koongo\Model\Channel\Profile\Manager->runProfile()
#7 /public_html/vendor/koongo-com/magento2-data-feed-manager/src/Nostress/Koongo/Model/Channel/Profile/Manager.php(155): Nostress\Koongo\Model\Channel\Profile\Manager->runProfiles()
#8 /public_html/vendor/koongo-com/magento2-data-feed-manager/src/Nostress/Koongo/Controller/Adminhtml/Channel/Profile/Execute.php(46): Nostress\Koongo\Model\Channel\Profile\Manager->runProfilesByIds()
#9 /public_html/vendor/magento/framework/Interception/Interceptor.php(58): Nostress\Koongo\Controller\Adminhtml\Channel\Profile\Execute->execute()
#10 /public_html/vendor/magento/framework/Interception/Interceptor.php(138): Nostress\Koongo\Controller\Adminhtml\Channel\Profile\Execute\Interceptor->___callParent()
#11 /public_html/vendor/magento/framework/Interception/Interceptor.php(153): Nostress\Koongo\Controller\Adminhtml\Channel\Profile\Execute\Interceptor->Magento\Framework\Interception\{closure}()
#12 /public_html/generated/code/Nostress/Koongo/Controller/Adminhtml/Channel/Profile/Execute/Interceptor.php(23): Nostress\Koongo\Controller\Adminhtml\Channel\Profile\Execute\Interceptor->___callPlugins()
#13 /public_html/vendor/magento/framework/App/Action/Action.php(111): Nostress\Koongo\Controller\Adminhtml\Channel\Profile\Execute\Interceptor->execute()
#16 /public_html/vendor/magento/framework/Interception/Interceptor.php(138): Nostress\Koongo\Controller\Adminhtml\Channel\Profile\Execute\Interceptor->___callParent()
#17 /public_html/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(145): Nostress\Koongo\Controller\Adminhtml\Channel\Profile\Execute\Interceptor->Magento\Framework\Interception\{closure}()
#19 /public_html/vendor/magento/framework/Interception/Interceptor.php(153): Nostress\Koongo\Controller\Adminhtml\Channel\Profile\Execute\Interceptor->Magento\Framework\Interception\{closure}()
#20 /public_html/generated/code/Nostress/Koongo/Controller/Adminhtml/Channel/Profile/Execute/Interceptor.php(32): Nostress\Koongo\Controller\Adminhtml\Channel\Profile\Execute\Interceptor->___callPlugins()
#21 /public_html/vendor/magento/framework/App/FrontController.php(245): Nostress\Koongo\Controller\Adminhtml\Channel\Profile\Execute\Interceptor->dispatch()
#31 {main} {"exception":"[object] (ParseError(code: 0): syntax error, unexpected identifier \"Angelo\" at /public_html/vendor/koongo-com/magento2-data-feed-manager/src/Nostress/Koongo/Model/Data/Transformation/Xml.php(540) : eval()'d code:1)"} []`

**Comment by MrTieGuy06** [comment]
I made a pull request for this issue #23.
Simple but effective :)

**Comment by IlyaZha** [comment]
@MrTieGuy06 Hello! We merged it and released a [new version ](https://github.com/koongo-com/magento2-data-feed-manager/releases/tag/2.4.8.17). Please, try it.
