### ISSUE TITLE
Block NameInLayout null. Exception Deprecated Functionality: stripos()

### ISSUE THREAD

**Issue by sergiuec** [koongo-com/magento2-data-feed-manager#4]
The following exception is thrown when "edit attributes" section is open in developer mode:

Exception #0 (Exception): Deprecated Functionality: stripos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/html/vendor/magento/module-price-permissions/Observer/AdminhtmlBlockHtmlBeforeObserver.php on line 125

Exception #0 (Exception): Deprecated Functionality: stripos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/html/vendor/magento/module-price-permissions/Observer/AdminhtmlBlockHtmlBeforeObserver.php on line 125
<pre>#1 stripos() called at [vendor/magento/module-price-permissions/Observer/AdminhtmlBlockHtmlBeforeObserver.php:125]
#2 Magento\PricePermissions\Observer\AdminhtmlBlockHtmlBeforeObserver->execute() called at [vendor/magento/framework/Event/Invoker/InvokerDefault.php:88]
#3 Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod() called at [vendor/magento/framework/Event/Invoker/InvokerDefault.php:74]
#4 Magento\Framework\Event\Invoker\InvokerDefault->dispatch() called at [vendor/magento/module-staging/Model/Event/Manager.php:97]
#5 Magento\Staging\Model\Event\Manager->dispatch() called at [generated/code/Magento/Staging/Model/Event/Manager/Proxy.php:95]
#6 Magento\Staging\Model\Event\Manager\Proxy->dispatch() called at [vendor/magento/module-backend/Block/Template.php:140]
#7 Magento\Backend\Block\Template->_toHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1117]
#8 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1121]
#9 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:670]
#10 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [generated/code/Nostress/Koongo/Block/Widget/Form/Renderer/Fieldset/Interceptor.php:356]
#11 Nostress\Koongo\Block\Widget\Form\Renderer\Fieldset\Interceptor->toHtml() called at [vendor/magento/module-backend/Block/Widget/Form/Renderer/Fieldset.php:50]
#12 Magento\Backend\Block\Widget\Form\Renderer\Fieldset->render() called at [generated/code/Nostress/Koongo/Block/Widget/Form/Renderer/Fieldset/Interceptor.php:32]
#13 Nostress\Koongo\Block\Widget\Form\Renderer\Fieldset\Interceptor->render() called at [vendor/magento/framework/Data/Form/Element/AbstractElement.php:541]
#14 Magento\Framework\Data\Form\Element\AbstractElement->getHtml() called at [generated/code/Magento/Framework/Data/Form/Element/Fieldset/Interceptor.php:338]
#15 Magento\Framework\Data\Form\Element\Fieldset\Interceptor->getHtml() called at [vendor/magento/framework/Data/Form/Element/AbstractElement.php:555]
#16 Magento\Framework\Data\Form\Element\AbstractElement->toHtml() called at [generated/code/Magento/Framework/Data/Form/Element/Fieldset/Interceptor.php:347]
#17 Magento\Framework\Data\Form\Element\Fieldset\Interceptor->toHtml() called at [vendor/magento/framework/Data/Form.php:373]
#18 Magento\Framework\Data\Form->toHtml() called at [vendor/magento/framework/Data/Form.php:390]
#19 Magento\Framework\Data\Form->getHtml() called at [vendor/magento/module-backend/Block/Widget/Form.php:113]
#20 Magento\Backend\Block\Widget\Form->getFormHtml() called at [generated/code/Nostress/Koongo/Block/Adminhtml/Channel/Profile/General/Edit/Tab/Main/Interceptor.php:68]
#21 Nostress\Koongo\Block\Adminhtml\Channel\Profile\General\Edit\Tab\Main\Interceptor->getFormHtml() called at [vendor/magento/module-backend/view/adminhtml/templates/widget/form.phtml:13]
#22 include() called at [vendor/magento/framework/View/TemplateEngine/Php.php:71]
#23 Magento\Framework\View\TemplateEngine\Php->render() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#24 Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#25 Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#26 Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php:23]
#27 Magento\Framework\View\TemplateEngine\Php\Interceptor->render() called at [vendor/magento/framework/View/Element/Template.php:263]
#28 Magento\Framework\View\Element\Template->fetchView() called at [generated/code/Nostress/Koongo/Block/Adminhtml/Channel/Profile/General/Edit/Tab/Main/Interceptor.php:221]
#29 Nostress\Koongo\Block\Adminhtml\Channel\Profile\General\Edit\Tab\Main\Interceptor->fetchView() called at [vendor/magento/framework/View/Element/Template.php:293]
#30 Magento\Framework\View\Element\Template->_toHtml() called at [vendor/magento/module-backend/Block/Template.php:141]
#31 Magento\Backend\Block\Template->_toHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1117]
#32 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1121]
#33 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:670]
#34 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [generated/code/Nostress/Koongo/Block/Adminhtml/Channel/Profile/General/Edit/Tab/Main/Interceptor.php:446]
#35 Nostress\Koongo\Block\Adminhtml\Channel\Profile\General\Edit\Tab\Main\Interceptor->toHtml() called at [vendor/magento/framework/View/Layout.php:578]
#36 Magento\Framework\View\Layout->_renderBlock() called at [vendor/magento/framework/View/Layout.php:555]
#37 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:149]
#38 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#39 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:140]
#40 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#41 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#42 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:149]
#43 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#44 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:140]
#45 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Element/AbstractBlock.php:517]
#46 Magento\Framework\View\Element\AbstractBlock->getChildHtml() called at [generated/code/Nostress/Koongo/Block/Adminhtml/Channel/Profile/General/Edit/Tabs/Interceptor.php:509]
#47 Nostress\Koongo\Block\Adminhtml\Channel\Profile\General\Edit\Tabs\Interceptor->getChildHtml() called at [vendor/koongo-com/magento2-data-feed-manager/src/Nostress/Koongo/Block/Adminhtml/Channel/Profile/General/Edit/Tabs.php:74]
#48 Nostress\Koongo\Block\Adminhtml\Channel\Profile\General\Edit\Tabs->_beforeToHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1116]
#49 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1121]
#50 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:670]
#51 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [generated/code/Nostress/Koongo/Block/Adminhtml/Channel/Profile/General/Edit/Tabs/Interceptor.php:572]
#52 Nostress\Koongo\Block\Adminhtml\Channel\Profile\General\Edit\Tabs\Interceptor->toHtml() called at [vendor/magento/framework/View/Layout.php:578]
#53 Magento\Framework\View\Layout->_renderBlock() called at [vendor/magento/framework/View/Layout.php:555]
#54 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:149]
#55 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#56 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:140]
#57 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#58 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#59 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:149]
#60 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#61 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:140]
#62 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#63 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#64 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:149]
#65 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#66 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:140]
#67 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#68 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#69 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:149]
#70 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#71 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:140]
#72 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#73 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#74 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:149]
#75 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#76 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:140]
#77 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#78 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#79 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:149]
#80 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#81 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:140]
#82 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#83 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#84 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:149]
#85 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#86 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:140]
#87 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#88 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#89 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:149]
#90 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#91 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:140]
#92 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:975]
#93 Magento\Framework\View\Layout->getOutput() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:347]
#94 Magento\Framework\View\Layout\Interceptor->getOutput() called at [vendor/magento/framework/View/Result/Page.php:260]
#95 Magento\Framework\View\Result\Page->render() called at [vendor/magento/framework/View/Result/Layout.php:171]
#96 Magento\Framework\View\Result\Layout->renderResult() called at [generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php:140]
#97 Magento\Backend\Model\View\Result\Page\Interceptor->renderResult() called at [vendor/magento/framework/App/Http.php:120]
#98 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:23]
#99 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
#100 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:73]
</pre>

The following error is thrown in browser console while magento is in production mode:

<pre>
(index):10 Uncaught TypeError: Cannot read properties of null (reading 'selectedIndex')
    at updateShippingTable ((index):2699:74)
    at (index):2923:4
    at nrWrapper ((index):10:14381)
</pre>

And all tabs in this section are empty. Only attributes mapping table is displayed.
![image](https://github.com/koongo-com/magento2-data-feed-manager/assets/71697003/41a00d29-32ba-49fc-91bf-c359e7bfdf18)

Module Version: koongo-com/magento2-data-feed-manager 2.4.8.6
Adobe Commerce Cloud 2.4.5-p3
PHP 8.1

**Comment by IlyaZha** [comment]
Hello! I created a fix, based on your information: https://github.com/koongo-com/magento2-data-feed-manager/pull/5 I hope it helps.

**Comment by IlyaZha** [comment]
@sergiuec We released an update https://github.com/koongo-com/magento2-data-feed-manager/releases/tag/2.4.8.8 It should help.
