### ISSUE TITLE
A Feed generation fails on the Koongo module version 2.4.8.8

### ISSUE THREAD

**Issue by zaietsv** [koongo-com/magento2-data-feed-manager#9]
A Feed generation fails on the Koongo module version 2.4.8.8
```
[2023-09-06 15:05:14] [42S22][1054] (conn=520) Unknown column 'qty_decimal' in 'field list'

INSERT INTO nostress_koongo_cache_product (product_id, store_id, qty, stock_status, qty_decimal)
           SELECT cpf2.entity_id AS product_id,
                  (2)                AS store_id,
                  ROUND(ciss.qty, 0) AS qty,
                  ciss.stock_status,
                  ciss.qty       AS qty_decimal
           FROM catalog_product_flat_2 AS cpf2
                    LEFT JOIN cataloginventory_stock_status AS ciss
                              ON cpf2.entity_id = ciss.product_id AND ciss.stock_id = 1 AND ciss.website_id = 0
```
![image](https://github.com/koongo-com/magento2-data-feed-manager/assets/14337245/f9522061-1fdb-45d8-ab0d-90e5788d7f34)

**Comment by IlyaZha** [comment]
@zaietsv Thank you for your report, I'll take care of it

**Comment by zaietsv** [comment]
`Exception #0 (Exception): Asymmetric transaction rollback.

Exception #0 (Exception): Asymmetric transaction rollback.
<pre>#1 Magento\Framework\DB\Adapter\Pdo\Mysql\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#2 Magento\Framework\DB\Adapter\Pdo\Mysql\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#3 Magento\Framework\DB\Adapter\Pdo\Mysql\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/DB/Adapter/Pdo/Mysql/Interceptor.php:32]
#4 Magento\Framework\DB\Adapter\Pdo\Mysql\Interceptor->rollBack() called at [vendor/magento/framework/Model/ResourceModel/Db/TransactionManager.php:46]
#5 Magento\Framework\Model\ResourceModel\Db\TransactionManager->rollBack() called at [vendor/koongo-com/magento2-data-feed-manager/src/Nostress/Koongo/Model/ResourceModel/AbstractResourceModel.php:75]
#6 Nostress\Koongo\Model\ResourceModel\AbstractResourceModel->runQuery() called at [vendor/koongo-com/magento2-data-feed-manager/src/Nostress/Koongo/Model/ResourceModel/Cache/Product.php:107]
#7 Nostress\Koongo\Model\ResourceModel\Cache\Product->insertRecords() called at [vendor/koongo-com/magento2-data-feed-manager/src/Nostress/Koongo/Model/ResourceModel/Cache/Product.php:85]
#8 Nostress\Koongo\Model\ResourceModel\Cache\Product->reloadTable() called at [vendor/koongo-com/magento2-data-feed-manager/src/Nostress/Koongo/Model/ResourceModel/Cache.php:48]
#9 Nostress\Koongo\Model\ResourceModel\Cache->reload() called at [vendor/koongo-com/magento2-data-feed-manager/src/Nostress/Koongo/Model/Cache.php:36]
#10 Nostress\Koongo\Model\Cache->reload() called at [vendor/koongo-com/magento2-data-feed-manager/src/Nostress/Koongo/Model/Cache/Manager.php:181]
#11 Nostress\Koongo\Model\Cache\Manager->reloadAllCache() called at [vendor/koongo-com/magento2-data-feed-manager/src/Nostress/Koongo/Model/Channel/Profile/Manager.php:341]
#12 Nostress\Koongo\Model\Channel\Profile\Manager->reloadCache() called at [vendor/koongo-com/magento2-data-feed-manager/src/Nostress/Koongo/Model/Channel/Profile/Manager.php:180]
#13 Nostress\Koongo\Model\Channel\Profile\Manager->runProfiles() called at [vendor/koongo-com/magento2-data-feed-manager/src/Nostress/Koongo/Model/Channel/Profile/Manager.php:155]
#14 Nostress\Koongo\Model\Channel\Profile\Manager->runProfilesByIds() called at [vendor/koongo-com/magento2-data-feed-manager/src/Nostress/Koongo/Controller/Adminhtml/Channel/Profile/Execute.php:46]
#15 Nostress\Koongo\Controller\Adminhtml\Channel\Profile\Execute->execute() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#16 Nostress\Koongo\Controller\Adminhtml\Channel\Profile\Execute\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#17 Nostress\Koongo\Controller\Adminhtml\Channel\Profile\Execute\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#18 Nostress\Koongo\Controller\Adminhtml\Channel\Profile\Execute\Interceptor->___callPlugins() called at [generated/code/Nostress/Koongo/Controller/Adminhtml/Channel/Profile/Execute/Interceptor.php:23]
#19 Nostress\Koongo\Controller\Adminhtml\Channel\Profile\Execute\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:111]
#20 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/module-backend/App/AbstractAction.php:151]
#21 Magento\Backend\App\AbstractAction->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#22 Nostress\Koongo\Controller\Adminhtml\Channel\Profile\Execute\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#23 Nostress\Koongo\Controller\Adminhtml\Channel\Profile\Execute\Interceptor->Magento\Framework\Interception\{closure}() called at [app/code/WeltPixel/Backend/Plugin/Utility.php:76]
#24 WeltPixel\Backend\Plugin\Utility->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#25 Nostress\Koongo\Controller\Adminhtml\Channel\Profile\Execute\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:145]
#26 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#27 Nostress\Koongo\Controller\Adminhtml\Channel\Profile\Execute\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#28 Nostress\Koongo\Controller\Adminhtml\Channel\Profile\Execute\Interceptor->___callPlugins() called at [generated/code/Nostress/Koongo/Controller/Adminhtml/Channel/Profile/Execute/Interceptor.php:32]
#29 Nostress\Koongo\Controller\Adminhtml\Channel\Profile\Execute\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:245]
#30 Magento\Framework\App\FrontController->getActionResponse() called at [vendor/magento/framework/App/FrontController.php:212]
#31 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:147]
#32 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#33 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#34 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#35 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23]
#36 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#37 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#38 Magento\Framework\App\Http\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#39 Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#40 Magento\Framework\App\Http\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:23]
#41 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
#42 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:30]`

**Comment by IlyaZha** [comment]
Hello, @zaietsv ! [New release](https://github.com/koongo-com/magento2-data-feed-manager/releases/tag/2.4.8.9) should resolve the issue.

**Comment by zaietsv** [comment]
Yes, I can approve it works. Thank you for the quick delivery!
